[workspace]

[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.8"
once_cell = "1.19.0"
regex = "1.10.3"
wit-bindgen = { version = "0.18.0", default-features = false, features = ["realloc", "macros"] }

[lib]
crate-type = ["cdylib"]
